name: Atualization of Main Branch

on: 
  push:
    branches:
      - develop

jobs:

  welcome:
    name: Welcome
    runs-on: ubuntu-latest
    steps:
      - name: Welcome
        run:
          echo "Hello World"
      
      - name: Assign author to issue
        uses: technote-space/assign-author@v1

  merge-branch:
    name: Update Main Branch
    runs-on: ubuntu-latest
    needs: [welcome]
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Config Git
        run: |
          git config --global user.mail "robot@github.com"
          git config --global user.name "Main Robot"
          git fetch --all

      - name: Merge on main
        run: |
          git checkout develop
          git pull origin develop
          git checkout main
          git pull origin main
          git merge develop
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}