name: Atualization of Main Branch

on: 
  issues:
    types: opened

concurrency:
  group: 'atualization-main'

jobs:
    welcome:
      if: contains(github.event.issue.labels.*.name, 'atualization-main')
      name: Welcome
      runs-on: ubuntu-latest
      steps:
        - name: Welcome
          run:
            echo "Hello World"
        
        # - name: Assign author to issue
        #   uses: technote-space/assign-author@v1

        - name: Save pipeline link on issue
          uses: peter-evans/create-or-update-comment@v2
          with:
            issue-number: ${{ github.event.issue.number }}
            body: |
              You can track the action execution in [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

    open-pull-request:
      name: Open Pull Request to Main
      runs-on: ubuntu-latest
      needs: [welcome]
      steps:
        - name: Checkout do Repositório
          uses: actions/checkout@v3

        - name: Open Pull Request
          uses: peter-evans/create-pull-request@v3
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            title: Atualization of Main Branch
            body: Atualization of main branch, with new develop
            branch: develop
            base: main